### ISSUE TITLE
reverse_proxy_default instead of reverseproxy_default

### ISSUE THREAD

**Issue by ThePraeceps** [420m/dockyard#21]
Hey,

I think the required network should be reverse_proxy_default not  reverseproxy_default - seems like a typo to me and it doesn't work otherwise.

Thanks

**Comment by ThePraeceps** [comment]
Also getting 404 page not found on all my subdomains if you could help out I'd appreciate it.

**Comment by hkaj** [comment]
Hi @ThePraeceps 
I have the same issue, it seems to be related to a recent update in traefik. I haven't had time to investigate it yet, but will give it a shot asap.

Re: network name, the `reverse_proxy` docker-compose creates a network named `reverseproxy_default`- on docker `17.05.0-ce` anyway. Do you see something different in your case, if so which version of docker?

**Comment by ThePraeceps** [comment]
Hey,
Thanks for the response.

Docker version 18.03.0-ce, build 0520e24, the dockyard docker_compse fails because that network isn't there after I've done all the setup including the reverse_proxy docker. 

Spinning up a VM to try again but I'm pretty confident that network didn't get created.

Trying to move over from a apache directory listing and rutorrent so any help would be appreciated.

**Comment by ThePraeceps** [comment]
Yeah "Creating network "reverse_proxy_default" with driver "bridge"

**Comment by ThePraeceps** [comment]
I'm also getting traefik complaining about the web network and I have no idea where that comes from 

"level=warning msg="Could not find network named 'web' for container '/dockyard_jackett_1'! Maybe you're missing the project's prefix in the label? Defaulting to first available network"

**Comment by hkaj** [comment]
hey @ThePraeceps 
I pushed an update on both repo that should help. There are some additional steps required (see https://github.com/hkaj/reverse_proxy#use-it) but it should work now. Docker changed the way networks are named by default apparently so there was some name inconsistency between docker versions.

Let me know how it goes :)

**Comment by ThePraeceps** [comment]
Hey, 

I found another solution that works very similarly but thanks for your help!
